---
language: node_js
node_js:
  - 12
  - 11
script:
  # use latest npm
  - npm install -g npm
  # install required global npm packages
  - npm install -g codecov
  # testing
  - npm i
  - npm i events # travis bug
  - npm test
after_success:
  # code coverage & codecov upload
  - npx nyc report --extension=.ts --reporter=text-lcov > .nyc_output/coverage.lcov
  - codecov
