---
language: node_js
node_js:
  - 12
  - 11
script:
  # use latest npm to work on node9
  - npm install -g npm
  # install required global npm packages
  - npm install -g codecov
  # testing
  - npm i
  - npm test
after_success:
  # code coverage & codecov upload
  - codecov
