---
language: node_js
node_js:
  - 12
  - 11
before_install:
  - npm i -g npm@6.10.2
before_script:
  - npm install -g codecov
  - npm i
script:
  - npm test
after_success:
  - npx nyc report --extension=.ts --reporter=text-lcov > .nyc_output/coverage.lcov
  - codecov
